# -*- coding: utf-8 -*-
"""PBI-Clustering.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TNN3a0N7COx_NyW4VezsZ1qRgorkLQTx
"""



"""Load Libraries dan Dataset"""

# library untuk pengolahan data
import pandas as pd
import numpy as np

# library untuk visualisasi data
import matplotlib.pyplot as plt
import seaborn as sns

# library untuk machine learning model
from sklearn.cluster import KMeans

df = pd.read_csv('Dataset CCV 6 - Clustering Model.csv')
df.head()

"""Eksploratory Data Analysis (EDA)"""

df.info()

df.isnull().sum()

plt.figure(figsize=(15,3))

plt.subplot(1,2,1)
sns.histplot(df['umur'], color='royalblue', kde = True)
plt.title('distribusi umur', fontsize=16)
plt.xlabel('umur', fontsize=14)
plt.ylabel('Frequency', fontsize=14)

plt.subplot(1,2,2)
sns.histplot(df['harga_pembelian'], color='deeppink', kde = True)
plt.title('distribusi pembayaran para pelanggan', fontsize=16)
plt.xlabel('harga_pembelian', fontsize=14)

plt.show()

"""Membuat visualisasi sebaran data"""

sns.lmplot(x='umur', y='harga_pembelian', data=df, fit_reg=False, hue='jenis_kelamin', height=5, palette='Dark2')
plt.title('umur vs harga yang dikeluarkan customer vs jenis kelamin', fontsize=14)
plt.xlabel('umur', fontsize=13)
plt.ylabel('harga pengeluaran', fontsize=13)
plt.show()

"""K-Means Clustering"""

X1=df[['umur', 'harga_pembelian']]
wcss=[]
for n in range(1,11):
  model1=KMeans(n_clusters=n, init='k-means++', n_init=10, max_iter=300, tol=0.0001, random_state=100)
  model1.fit(X1)
  wcss.append(model1.inertia_)
print(wcss)

plt.figure(figsize=(8,3))
plt.plot(list(range(1,11)), wcss, color='royalblue', marker='o', linewidth=2, markersize=12, markerfacecolor='m', markeredgecolor='m')
plt.title('WCSS vs Banyaknya Cluster', fontsize=18)
plt.xlabel('Jumlah Cluster', fontsize=15)
plt.ylabel('WCSS', fontsize=15)
plt.show()

"""Membuat model clustering dengan K yang optimal"""

model1=KMeans(n_clusters=n, init='k-means++', n_init=10, max_iter=300, tol=0.0001, random_state=100)
model1.fit(X1)
labels1=model1.labels_
centroids1=model1.cluster_centers_

plt.figure(figsize=(11,6))
sns.set_style('white')
plt.scatter(x=df['umur'], y=df['harga_pembelian'], c=labels1, cmap='winter')
plt.scatter(x = centroids1[:,0], y=centroids1[:,1], s=300, c='red')
plt.xlabel('umur', fontsize=15)
plt.ylabel('harga pembelian', fontsize=15)
plt.title('Segmentasi Pelanggan berdasarkan umur dan pembeliannya', fontsize=18)
plt.show()